/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravesseirosRouteImport } from './routes/travesseiros'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConjuntosBoxRouteImport } from './routes/conjuntos-box'
import { Route as ColchoesRouteImport } from './routes/colchoes'
import { Route as CabeceirasRouteImport } from './routes/cabeceiras'
import { Route as BuscaRouteImport } from './routes/busca'
import { Route as BoxBauRouteImport } from './routes/box-bau'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'

const TravesseirosRoute = TravesseirosRouteImport.update({
  id: '/travesseiros',
  path: '/travesseiros',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConjuntosBoxRoute = ConjuntosBoxRouteImport.update({
  id: '/conjuntos-box',
  path: '/conjuntos-box',
  getParentRoute: () => rootRouteImport,
} as any)
const ColchoesRoute = ColchoesRouteImport.update({
  id: '/colchoes',
  path: '/colchoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CabeceirasRoute = CabeceirasRouteImport.update({
  id: '/cabeceiras',
  path: '/cabeceiras',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscaRoute = BuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxBauRoute = BoxBauRouteImport.update({
  id: '/box-bau',
  path: '/box-bau',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/box-bau': typeof BoxBauRoute
  '/busca': typeof BuscaRoute
  '/cabeceiras': typeof CabeceirasRoute
  '/colchoes': typeof ColchoesRoute
  '/conjuntos-box': typeof ConjuntosBoxRoute
  '/contato': typeof ContatoRoute
  '/ofertas': typeof OfertasRoute
  '/sobre': typeof SobreRoute
  '/travesseiros': typeof TravesseirosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/box-bau': typeof BoxBauRoute
  '/busca': typeof BuscaRoute
  '/cabeceiras': typeof CabeceirasRoute
  '/colchoes': typeof ColchoesRoute
  '/conjuntos-box': typeof ConjuntosBoxRoute
  '/contato': typeof ContatoRoute
  '/ofertas': typeof OfertasRoute
  '/sobre': typeof SobreRoute
  '/travesseiros': typeof TravesseirosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/box-bau': typeof BoxBauRoute
  '/busca': typeof BuscaRoute
  '/cabeceiras': typeof CabeceirasRoute
  '/colchoes': typeof ColchoesRoute
  '/conjuntos-box': typeof ConjuntosBoxRoute
  '/contato': typeof ContatoRoute
  '/ofertas': typeof OfertasRoute
  '/sobre': typeof SobreRoute
  '/travesseiros': typeof TravesseirosRoute
  '/produto/$slug': typeof ProdutoSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/box-bau'
    | '/busca'
    | '/cabeceiras'
    | '/colchoes'
    | '/conjuntos-box'
    | '/contato'
    | '/ofertas'
    | '/sobre'
    | '/travesseiros'
    | '/produto/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/box-bau'
    | '/busca'
    | '/cabeceiras'
    | '/colchoes'
    | '/conjuntos-box'
    | '/contato'
    | '/ofertas'
    | '/sobre'
    | '/travesseiros'
    | '/produto/$slug'
  id:
    | '__root__'
    | '/'
    | '/box-bau'
    | '/busca'
    | '/cabeceiras'
    | '/colchoes'
    | '/conjuntos-box'
    | '/contato'
    | '/ofertas'
    | '/sobre'
    | '/travesseiros'
    | '/produto/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoxBauRoute: typeof BoxBauRoute
  BuscaRoute: typeof BuscaRoute
  CabeceirasRoute: typeof CabeceirasRoute
  ColchoesRoute: typeof ColchoesRoute
  ConjuntosBoxRoute: typeof ConjuntosBoxRoute
  ContatoRoute: typeof ContatoRoute
  OfertasRoute: typeof OfertasRoute
  SobreRoute: typeof SobreRoute
  TravesseirosRoute: typeof TravesseirosRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travesseiros': {
      id: '/travesseiros'
      path: '/travesseiros'
      fullPath: '/travesseiros'
      preLoaderRoute: typeof TravesseirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conjuntos-box': {
      id: '/conjuntos-box'
      path: '/conjuntos-box'
      fullPath: '/conjuntos-box'
      preLoaderRoute: typeof ConjuntosBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colchoes': {
      id: '/colchoes'
      path: '/colchoes'
      fullPath: '/colchoes'
      preLoaderRoute: typeof ColchoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabeceiras': {
      id: '/cabeceiras'
      path: '/cabeceiras'
      fullPath: '/cabeceiras'
      preLoaderRoute: typeof CabeceirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/busca': {
      id: '/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof BuscaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-bau': {
      id: '/box-bau'
      path: '/box-bau'
      fullPath: '/box-bau'
      preLoaderRoute: typeof BoxBauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoxBauRoute: BoxBauRoute,
  BuscaRoute: BuscaRoute,
  CabeceirasRoute: CabeceirasRoute,
  ColchoesRoute: ColchoesRoute,
  ConjuntosBoxRoute: ConjuntosBoxRoute,
  ContatoRoute: ContatoRoute,
  OfertasRoute: OfertasRoute,
  SobreRoute: SobreRoute,
  TravesseirosRoute: TravesseirosRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
